"""initial_schema

Revision ID: 5a89a0151cad
Revises: 
Create Date: 2026-03-20 12:47:06.951586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a89a0151cad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparisons',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('person_a_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('person_b_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('similarity_method', sa.Enum('cosine', 'euclidean', 'procrustes', name='similarity_method'), server_default=sa.text("'cosine'"), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_a_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_b_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_a_id', 'person_b_id', 'similarity_method', name='uq_comparison')
    )
    op.create_table('images',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('person_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'validating', 'analyzing', 'analyzed', 'error', name='image_status'), server_default=sa.text("'uploaded'"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_features',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('person_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('method', sa.Enum('average', 'single', 'median', name='aggregation_method'), server_default=sa.text("'average'"), nullable=False),
    sa.Column('feature_vector', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_table('features',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('image_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('landmarks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_vector', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('features')
    op.drop_table('person_features')
    op.drop_table('images')
    op.drop_table('comparisons')
    op.drop_table('persons')
    # Enum 型を明示的に削除（autogenerate では含まれないため手動追加）
    # op.get_bind() は SQLAlchemy 2.0 async 環境で MissingGreenlet エラーになるため op.execute を使用
    op.execute("DROP TYPE IF EXISTS aggregation_method")
    op.execute("DROP TYPE IF EXISTS image_status")
    op.execute("DROP TYPE IF EXISTS similarity_method")
    # ### end Alembic commands ###
